WebsiteXemPhim/Controllers/XemPhimController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebsiteXemPhim.DataAccess;
using WebsiteXemPhim.Models;

namespace WebsiteXemPhim.Controllers
{
    public class XemPhimController : Controller
    {
        private readonly ApplicationDbContext _context;

        public XemPhimController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> XemPhimBo(int id,int tap)
        {
            var BinhLuan = await _context.BinhLuan
            .Include(b => b.User) 
            .Where(b => b.PhimBoId == id).OrderByDescending(p=>p.BinhLuanId)
            .ToListAsync(); 
            var TheLoai = _context.TheLoai.ToList();
            var QuocGia = _context.QuocGia.ToList();
            var Nam = _context.Nam.ToList();
            var TapPhim = _context.TapPhim.Include(p => p.PhimBo).Where(p => p.PhimBoId == id).OrderByDescending(p=>p.Tap).ToList();
            var temp = _context.TapPhim.Include(p => p.PhimBo).Where(p => p.PhimBoId == id && p.Tap == 1);
            // Lấy thông tin phim hiện tại, bao gồm thể loại qua bảng ChiTietTheLoaiPhimBos
            var phimBo = await _context.PhimBo
                .Include(p => p.ChiTietTheLoaiPhimBos)
                .ThenInclude(ct => ct.TheLoai) // Lấy dữ liệu thể loại
                .FirstOrDefaultAsync(p => p.PhimBoId == id);

            if (phimBo == null)
            {
                return NotFound();
            }

            // Lấy danh sách các thể loại của phim hiện tại
            var theLoaiIds = phimBo.ChiTietTheLoaiPhimBos
                .Select(ct => ct.TheLoaiId)
                .ToList();

            // Tìm các phim có cùng thể loại, loại trừ phim hiện tại
            var phimGoiY = await _context.PhimBo
                .Include(p => p.ChiTietTheLoaiPhimBos)
                .Where(p => p.PhimBoId != id &&
                            p.ChiTietTheLoaiPhimBos.Any(ct => theLoaiIds.Contains(ct.TheLoaiId))) // Có ít nhất một thể loại trùng
                .OrderByDescending(p => p.LuotXem)
                .Take(10) // Giới hạn 10 phim
                .ToListAsync();
            ViewBag.BinhLuanThoiGian = BinhLuan.ToDictionary(b => b.BinhLuanId, b => ThoiGianTruoc(b.NgayTao));
            ViewData["PhimGoiY"] = phimGoiY;
            ViewData["TheLoai"] = TheLoai;
            ViewData["QuocGia"] = QuocGia;
            ViewData["Nam"] = Nam;
            ViewData["TapPhim"] = TapPhim;
            ViewData["Tap"] = tap;
            ViewData["BinhLuan"] = BinhLuan;
            var PhimBoesQuery = _context.TapPhim.Include(p => p.PhimBo).Where(p => p.PhimBoId == id && p.Tap==tap);
            return View(PhimBoesQuery);
        }
        public async Task<IActionResult> XemPhimLe(int id)
        {
            var TheLoai = _context.TheLoai.ToList();
            var QuocGia = _context.QuocGia.ToList();
            var Nam = _context.Nam.ToList();
            var BinhLuan = await _context.BinhLuan
                .Include(b => b.User)
                .Where(b => b.PhimLeId == id)
                .OrderByDescending(p => p.BinhLuanId)
                .ToListAsync();

            // Lấy thông tin phim hiện tại, bao gồm thể loại qua bảng ChiTietTheLoaiPhimLes
            var phimLe = await _context.PhimLe
                .Include(p => p.ChiTietTheLoaiPhimLes)
                .ThenInclude(ct => ct.TheLoai) // Lấy dữ liệu thể loại
                .FirstOrDefaultAsync(p => p.PhimLeId == id);

            if (phimLe == null)
            {
                return NotFound();
            }

            // Lấy danh sách các thể loại của phim hiện tại
            var theLoaiIds = phimLe.ChiTietTheLoaiPhimLes
                .Select(ct => ct.TheLoaiId)
                .ToList();

            // Tìm các phim có cùng thể loại, loại trừ phim hiện tại
            var phimGoiY = await _context.PhimLe
                .Include(p => p.ChiTietTheLoaiPhimLes)
                .Where(p => p.PhimLeId != id &&
                            p.ChiTietTheLoaiPhimLes.Any(ct => theLoaiIds.Contains(ct.TheLoaiId))) // Có ít nhất một thể loại trùng
                .OrderByDescending(p => p.LuotXem)
                .Take(8) // Giới hạn 8 phim
                .ToListAsync();
            ViewBag.BinhLuanThoiGian = BinhLuan.ToDictionary(b => b.BinhLuanId, b => ThoiGianTruoc(b.NgayTao));
            ViewData["PhimGoiY"] = phimGoiY;
            ViewData["BinhLuan"] = BinhLuan;
            ViewData["TheLoai"] = TheLoai;
            ViewData["QuocGia"] = QuocGia;
            ViewData["Nam"] = Nam;

            return View(phimLe);
        }
        public string ThoiGianTruoc(DateTime NgayTao)
        {
            TimeSpan timeSinceCreation = DateTime.Now - NgayTao;
            if (timeSinceCreation.TotalMinutes < 1)
            {
                return "vừa xong";
            }
            else if (timeSinceCreation.TotalMinutes < 60)
            {
                return $"{(int)timeSinceCreation.TotalMinutes} phút trước";
            }
            else if (timeSinceCreation.TotalHours < 24)
            {
                return $"{(int)timeSinceCreation.TotalHours} giờ trước";
            }
            else if (timeSinceCreation.TotalDays < 30)
            {
                return $"{(int)timeSinceCreation.TotalDays} ngày trước";
            }
            else if (timeSinceCreation.TotalDays < 365)
            {
                return $"{(int)(timeSinceCreation.TotalDays / 30)} tháng trước";
            }
            else
            {
                return $"{(int)(timeSinceCreation.TotalDays / 365)} năm trước";
            }
        }
    }
}

WebsiteXemPhim/Views/XemPhim/XemPhimBo.cshtml
@model IEnumerable<WebsiteXemPhim.Models.TapPhim>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<section class="anime-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="anime__video__player">
                    @foreach (var item in Model)
                    {
                        <div class="video-container">
                            <iframe id="videoFrame" src="@item.Link" frameborder="0" scrolling="0" allowfullscreen></iframe>
                        </div>
                    }
                </div>
                <div class="anime__details__episodes">
                    <div class="section-title">
                        <h5>Danh sách tập phim</h5>
                    </div>
                    <div class="danhSachTapPhim">
                        @foreach (var tap in ViewData["TapPhim"] as List<TapPhim>)
                        {
                            <a asp-controller="XemPhim" asp-action="XemPhimBo" asp-route-id="@tap.PhimBoId" asp-route-tap="@tap.Tap" class="tapPhim @(ViewData["Tap"] != null && (int)ViewData["Tap"] == tap.Tap ? "active" : "")" data-src="@tap.Link"> Tập @(tap.Tap)</a>
                        }
                    </div>
                </div>
                @foreach (var item in Model)
                {
                    <div class="anime__details__form mb-5">
                        <div class="section-title">
                            <h5>Bình Luận</h5>
                        </div>
                        <form action="/BinhLuan/AddBinhLuanPB" method="post">
                            <textarea name="text" placeholder="Bình luận của tôi"></textarea>
                            <input type="hidden" name="phimboid" value="@item.PhimBo.PhimBoId" /> 
                            <button type="submit"><i class="fa fa-location-arrow"></i> Gửi</button>
                        </form>
                    </div>
                }
                <div class="anime__details__review">
                    <div class="section-title">
                        <h5>Ý Kiến Người Dùng</h5>
                    </div>
                    @foreach (var item in ViewData["BinhLuan"] as List<BinhLuan>)
                    {
                        var thoiGian = ViewBag.BinhLuanThoiGian[item.BinhLuanId];
                        <div class="anime__review__item">
                            <div class="anime__review__item__pic">
                                <img src="@(item.User.avatar ?? "/frontend/img/anime/Avatar.jpg")" alt="Error">
                            </div>
                            <div class="anime__review__item__text">
                                <h6>@item.User.UserName - <span>@thoiGian</span></h6>
                                <p>
                                    @item.NoiDungBinhLuan
                                </p>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="col-lg-4">
                <!-- Sidebar gợi ý phim -->
                <div class="section-title">
                    <form asp-controller="ChiTietPhim" asp-action="XemPhimNgauNhien" method="get">
                        <button type="submit" class="btn btn-primary">XEM PHIM NGẪU NHIÊN</button>
                    </form>
                </div>
                <div class="anime__details__form mb-5">
                    <div class="section-title">
                        <h5>Phim liên quan</h5>
                    </div>
                    @foreach (var phim in ViewData["PhimGoiY"] as List<PhimBo>)
                    {
                        <div class="anime__sidebar__item">
                            <!-- Hình ảnh -->
                            <div class="anime__sidebar__item__pic">
                                <img src="@phim.AnhNen" alt="@phim.TenPhim">
                            </div>
                            <!-- Chữ -->
                            <div class="anime__sidebar__item__text">
                                <h5>
                                    <a href="/ChiTietPhim/ChiTietPhimBo/@phim.PhimBoId">
                                        <b>@phim.TenPhim</b>
                                    </a>
                                </h5>
                                <span>Lượt xem @phim.LuotXem</span>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

WebsiteXemPhim/Views/XemPhim/XemPhimLe.cshtml
@model WebsiteXemPhim.Models.PhimLe
@{
    ViewData["Title"] = "XemPhimLe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="anime-details spad">
    <div class="container">
        <div class="row">
            <!-- Cột bên trái: Video -->
            <div class="col-lg-8">
                <div class="anime__video__player">
                    <div class="video-container">
                        <iframe id="videoFrame" src="@Model.Link" frameborder="0" scrolling="0" allowfullscreen></iframe>
                    </div>
                </div>
                <div class="anime__details__review">
                    <!-- Bình luận -->
                    <div class="anime__details__form mb-5">
                        <div class="section-title">
                            <h5>Bình Luận</h5>
                        </div>
                        <form action="/BinhLuan/AddBinhLuanPL" method="post">
                            <textarea name="text" placeholder="Bình luận của tôi"></textarea>
                            <input type="hidden" name="phimleid" value="@Model.PhimLeId" />
                            <button type="submit"><i class="fa fa-location-arrow"></i> Gửi</button>
                        </form>
                    </div>
                    <div class="section-title">
                        <h5>Ý Kiến Người Dùng</h5>
                    </div>
                    @foreach (var item in ViewData["BinhLuan"] as List<BinhLuan>)
                    {
                        var thoiGian = ViewBag.BinhLuanThoiGian[item.BinhLuanId];
                        <div class="anime__review__item">
                            <div class="anime__review__item__pic">
                                <img src="@(item.User.avatar ?? "/frontend/img/anime/Avatar.jpg")" alt="Error">
                            </div>
                            <div class="anime__review__item__text">
                                <h6>@item.User.UserName - <span>@thoiGian</span></h6>
                                <p>
                                    @item.NoiDungBinhLuan
                                </p>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="col-lg-4">
                <!-- Sidebar gợi ý phim -->
                <div class="section-title">
                    <form asp-controller="ChiTietPhim" asp-action="XemPhimNgauNhien" method="get">
                        <button type="submit" class="btn btn-primary">XEM PHIM NGẪU NHIÊN</button>
                    </form>
                </div>
                <div class="anime__details__form mb-5">
                    <div class="section-title">
                        <h5>Phim liên quan</h5>
                    </div>
                    @foreach (var phim in ViewData["PhimGoiY"] as List<PhimLe>)
                    {
                        <div class="anime__sidebar__item">
                            <!-- Hình ảnh -->
                            <div class="anime__sidebar__item__pic">
                                <img src="@phim.AnhNen" alt="@phim.TenPhim">
                            </div>
                            <!-- Chữ -->
                            <div class="anime__sidebar__item__text">
                                <h5>
                                    <a href="/ChiTietPhim/ChiTietPhimLe/@phim.PhimLeId">
                                        <b>@phim.TenPhim</b>
                                    </a>
                                </h5>
                                <span>@phim.ThoiLuong phút</span>
                                <span>Lượt xem @phim.LuotXem</span>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>